config/routes.rb
#custom routes for this plugin
if Rails::VERSION::MAJOR >= 3
  RedmineApp::Application.routes.draw do
    match 'issues/:issue_id/estimates', :controller => "estimates", :action => 'index', :method => :get, :as => :list_estimate_updates
  end
else
  ActionController::Routing::Routes.draw do |map|
    #http://redmine.espace.com.eg/projects/red-track/issues
    map.list_estimate_updates 'issues/:issue_id/estimates', :controller => "estimates", :action => 'index', :method => :get
  end
end

app/models/estimate_update.rb
class EstimateUpdate < ActiveRecord::Base
  belongs_to :issue
  validates_presence_of :issue_id,:old_estimated_hours,:new_estimated_hours
  def issue_created_on
    issue.created_on.to_date
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  include EstimatesHelper
  
  def index
    @issue = Issue.find(params[:issue_id])
    @estimates = EstimateUpdate.find(:all,
                                     :conditions=>{:issue_id=>params[:issue_id]},
                                     :order=>:created_at)
  end
  
end

app/helpers/estimates_helper.rb
module EstimatesHelper

  def time_tag(time)
    text = distance_of_time_in_words(Time.now, time)
    project = @issue.project
    link_to(text, {:controller => 'activities', :action => 'index', :id => @project, :from => User.current.time_to_date(time)}, :title => format_time(time))
  end

end

app/views/estimates/index.html.erb
<h3 class="issue"><%= @issue.subject %></h3>
<fieldset class="related-issues"><legend> Estimated time history</legend>
Estimated time : <%= @issue.estimated_hours %>
<% unless @estimates.empty? %>
	  <% @estimates.each do |e| -%>
      <h4><%= l(:label_updated_time, time_tag(e.updated_at)).html_safe %>.</h4>
	    <ul>
	      <%unless e.old_estimated_hours.blank?%>
	        <li>Changed from <%=e.old_estimated_hours%> to <%=e.new_estimated_hours%> </li>
	      <%else%>
	        <li>Changed set to <%=e.new_estimated_hours%></li>
	      <%end%>
	    </ul>
		<% end -%>
  
<%else%>
<p>No updates were made for this estimate</p>
<% end %>
</fieldset>

app/views/issues/_replace_text_with_link.html.erb
<script>
    var elements = $('td.estimated-hours');
    function replace_with_link(){
      var old_value = elements.html();
      elements.html('<a href="<%= list_estimate_updates_url(@issue) %>">' + old_value + '</a>');
    };
    
    $(document).ready( function(){
        replace_with_link();
    });
</script>